name: DeployAWS

on: 
  push:
    branches: 
      - server

jobs:
  buildMyLambda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: CD into lambda
      run: cd lambdas/emoji-rain-handler

    - name: Install dependencies
      run: npm i
    
    - name: Build using NCC
      run: npx ncc build index.ts -o dist/ncc

    - name: Create ZIP
      run: zip -j dist/deploy.zip ./dist/ncc/*
    