name: DeployAWS

on: 
  push:
    branches: 
      - server

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build Lambda
      run: |
        cd lambdas/emoji-rain-handler
        npm i
        npx ncc build index.ts -o dist/ncc
        zip -j dist/deploy.zip ./dist/ncc/*
    