name: DeployAWS

on: 
  push:
    branches: 
      - server

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./lambdas/emoji-rain-handler
      run: npm i

    - name: Build using NCC
      working-directory: ./lambdas/emoji-rain-handler
      run: npx ncc build index.ts -o dist/ncc

    - name: Create ZIP
      working-directory: ./lambdas/emoji-rain-handler
      run: zip -j dist/deploy.zip ./dist/ncc/*
    